# Numpy

## Hands On Excercises

### Array Operations and Broadcasting

Q1. Given a 3D array a with shape (2, 3, 4) and a 2D array b with shape (3, 4), perform element-wise multiplication between a and b using broadcasting.


In [1]:
import numpy as np

# 3D array
a = np.random.rand(2,3,4)

# 2 D array
b=np.random.rand(3,4)

result = a * b

print("Array a: ", a)
print("Array b: ", b)
print("Product of a * b : ", result)

Array a:  [[[0.68362008 0.77293103 0.52962335 0.82021777]
  [0.94455558 0.30615172 0.02217327 0.59891721]
  [0.88275056 0.52926198 0.88559906 0.20832882]]

 [[0.31268256 0.01100557 0.850071   0.78326612]
  [0.73718603 0.45910622 0.24036367 0.63034074]
  [0.72397559 0.99223395 0.41609789 0.54532252]]]
Array b:  [[0.59546758 0.11523849 0.27196634 0.09170038]
 [0.36172132 0.04116535 0.04465012 0.42454615]
 [0.48924635 0.05567376 0.11303764 0.43595234]]
Product of a * b :  [[[0.4070736  0.0890714  0.14403972 0.07521428]
  [0.34166589 0.01260284 0.00099004 0.254268  ]
  [0.43188249 0.029466   0.10010603 0.09082144]]

 [[0.18619233 0.00126827 0.2311907  0.0718258 ]
  [0.26665591 0.01889927 0.01073227 0.26760873]
  [0.35420241 0.05524139 0.04703472 0.23773463]]]


Q2. Implement a function that takes two 2D arrays c and d with different shapes and performs element-wise operations (addition, subtraction, multiplication, and division) between them using broadcasting. Handle the case where broadcasting is not possible.


In [2]:
def calculator(p,q):
  try:
    addition = p + q
    subtraction = p - q
    multiplication = c * d
    division = np.divide(p,q,out=np.zeros_like(p, dtype = float), where = q!=0)

    return {
        'Addition': addition,
        'Subtraction' : subtraction,
        "Multiplication" : multiplication,
        'division': division
    }

  except ValueError as e:
    return str(e)
  p = np.array([[1,2],[3,4],[5,6]])
  q = np.array([[1,2]])
  result = calculator(p,q)
  print("Addition: ", result['Addition'])
  print("Subtraction: ", result['Subtraction'])
  print("Multiplication: ", result['Multiplication'])
  print("Division: ", result['division'])





Q3. Create a 2D array e with shape (5, 3) and a 1D array f with length 5. Compute the outer product of e and f using broadcasting.

In [3]:
a1 = np.random.rand(5,3)
b1 = np.random.rand(5)

result1 = a1 * b1[:,np.newaxis]
print(result1)

[[0.6627403  0.44498422 0.5161768 ]
 [0.2443075  0.16955562 0.08932958]
 [0.37739633 0.76197192 0.51487856]
 [0.12094835 0.26016751 0.47797175]
 [0.56320216 0.05357015 0.6458817 ]]


### Indexing and Slicing

Given a 3D array g with shape (4, 3, 2), extract every other element along the first and second dimensions, but keep all elements along the third dimension.

In [5]:
a = np.random.rand(4,3,2)
result = a[::2, ::2, : ]
print(result)

[[[0.71250471 0.5672311 ]
  [0.86913924 0.07838704]]

 [[0.95335115 0.41900877]
  [0.34204025 0.7601897 ]]]


Create a function that takes a 2D array h and an array of row indices i and column indices j. The function should return a new array k where k[m, n] is the sum of the elements in h along the diagonal specified by i[m] and j[n].

In [12]:
def func(h,i,j):
  k = np.zeros((len(i),len(j)))
  for m, row in enumerate(i):
    for n, col in enumerate(j):
        diagonal_sum = 0
        x,y = row, col
        while x < h.shape[0] and y < h.shape[1]:
          diagonal_sum +=h[x,y]
          x+=1
          y+=1

          k[m,n] = diagonal_sum
  return k

  h = np.random.rand([4,4])
  i = [0,1]
  j = [1,2]
  k = func(h,i,j)
  print("Result: ",k)

Implement a function that takes a 2D array l and returns a new array m where each element in m is the product of the corresponding row and column means in l.

In [16]:
def func2(l):
  row = l.mean(axis=1)
  col = l.mean(axis=0)
  m = np.outer(row,col)
  return m
l  = np.random.rand(3,3)
res = func2(l)
print(res)


[[0.28243758 0.12024001 0.33245772]
 [0.2216916  0.09437908 0.26095353]
 [0.19915523 0.08478484 0.23442593]]


### Array Manipulation

Given a 2D array n with shape (4, 6), reshape it into a 3D array with shape (2, 2, 6) and then flatten it back to a 2D array with shape (4, 6).

In [17]:
n1 = np.arange(24).reshape(4,6)
n2 = n1.reshape(2,2,6)
n3 = n2.reshape(4,6)
print("Original 2D array : ",n1)
print("Reshaped to 3D array : ",n2)
print("Flattened back to 2D array : ",n3)


Original 2D array :  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Reshaped to 3D array :  [[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]
Flattened back to 2D array :  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


Implement a function that takes a 2D array o and rolls it along the first axis by a specified number of positions. For example, if the input array is [[1, 2, 3], [4, 5, 6]] and the number of positions is 1, the output should be [[4, 5, 6], [1, 2, 3]].

In [18]:
def func3(o, positions):
  array = np.roll(o,shift = positions, axis = 0)
  return array
o = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
positions = 2

final = func3(o,positions)
print("Array: ", final)

Array:  [[ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


Create a function that takes a 2D array p and replaces all occurrences of a specified value x with the mean of the neighboring elements (horizontally and vertically) in the array.

In [19]:

def func4(p,x):
  p_copy = p.copy()
  rows, cols = p.shape

  for i in range(rows):
    for j in range(cols):
      if p[i,j]== x :
        neighbors = []
        # left neighbor
        if j > 0:
          neighbors.append(p[i,j-1])
        # right neighbor
        if j < cols -1:
          neighbors.append(p[i,j+1])
        # top neighbor
        if i > 0:
          neighbors.append(p[i-1,j])
        # bottom neighbor
        if i < rows -1:
          neighbors.append(p[i+1,j])
        if neighbors:
          mean = np.mean(neighbors)
          p_copy[i,j] = mean

  return p_copy
p = np.array([[1,2,3],[4,-1,6],[7,8,-1]])
x=-1
result = func4(p,x)
print("Modified array:",result)


Modified array: [[1 2 3]
 [4 5 6]
 [7 8 7]]
